# Generated by Django 4.2.13 on 2024-06-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_remove_visitorpass_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitorpass",
            name="gender",
            field=models.CharField(default="Male", max_length=10),
        ),
        migrations.AlterField(
            model_name="visitorpass",
            name="aadhaar_number",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="visitorpass",
            name="mobile_number",
            field=models.CharField(max_length=15),
        ),
    ]
