# Generated by Django 4.2.13 on 2024-07-01 16:47

import datetime
from django.db import migrations, models
import home.models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_visitorpass_gender_alter_visitorpass_aadhaar_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitorpass",
            name="expiry_date",
            field=models.DateField(default=home.models.default_expiry_date),
        ),
        migrations.AlterField(
            model_name="visitorpass",
            name="date_of_visiting",
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
